version: '2.1'

services:
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'ciudadeshotel-network'
  cities-service:
    build: cities-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - 'ciudadeshotel-network'
  hotels-service:
    build: hotels-service
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - 'ciudadeshotel-network'

networks:
  ciudadeshotel-network: