INSERT INTO post (id, title, user_id)
VALUES
    (1, 'Introduction to Java Programming', 1),
    (2, 'Java Variables and Data Types', 2),
    (3, 'Object-Oriented Programming', 3),
    (4, 'Java Control Structures', 4),
    (5, 'Exception Handling in Java', 5),
    (6, 'Java Methods and Functions', 1),
    (7, 'Inheritance and Polymorphism', 2),
    (8, 'Java Collections Framework', 3),
    (9, 'File Handling in Java', 4),
    (10, 'Multithreading in Java', 5),
    (11, 'Java GUI Programming with Swing', 1),
    (12, 'Database Connectivity with JDBC', 2),
    (13, 'Introduction to JavaFX', 3),
    (14, 'Unit Testing in Java', 4),
    (15, 'RESTful Web Services with Java', 5),
    (16, 'Concurrency in Java', 1),
    (17, 'Java Reflection', 2),
    (18, 'Design Patterns in Java', 3),
    (19, 'Java Streams and Lambdas', 4),
    (20, 'Introduction to Spring Framework', 5),
    (21, 'Java Security', 1),
    (22, 'Java Serialization', 2),
    (23, 'Asynchronous Programming in Java', 3),
    (24, 'Java Performance Optimization', 4),
    (25, 'Microservices with Java and Spring Boot', 5),
    (26, 'Java 9 and Beyond', 1),
    (27, 'Java Module System', 2),
    (28, 'Machine Learning in Java', 3),
    (29, 'Java Native Interface (JNI)', 4),
    (30, 'Java Best Practices', 5);